- hosts: localhost
  gather_facts: true
  become: false
  tasks:
  - shell:
      cmd: terraform output public_ip
      chdir: /var/lib/jenkins/workspace/Lampstack-terraform/
    register: terraform

  - ansible.builtin.debug:
      var: terraform.stdout

  - shell:
      cmd: terraform output key > /var/lib/jenkins/workspace/Lampstack-terraform/sshkey.pem && chmod 400 /var/lib/jenkins/workspace/Lampstack-terraform/sshkey.pem &&  chown jenkins.jenkins /var/lib/jenkins/workspace/Lampstack-terraform/sshkey.pem 
      chdir: /var/lib/jenkins/workspace/Lampstack-terraform

  - name: Update Inventory
    ansible.builtin.add_host:
      name: "{{ item }}"
      groups: aws
      ansible_ssh_private_key_file: /var/lib/jenkins/workspace/Lampstack-terraform/sshkey.pem
      ansible_user: ubuntu
    loop: "{{ terraform.stdout }}"

- hosts: aws
  gather_facts: true
  become: true
  user: root
  tasks:
  - name: install lamp stack
    apt: name={{ item }} state=present update_cache=yes
    with_items:
        - apache2
        - mysql-server
        - php7.2
        - php7.2-mysql
  - name: start services
    service: name={{ item }} state=started enabled=yes
    with_items:
        - apache2
        - mysql

  - name: deploy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html 




