apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 414647299268.dkr.ecr.us-east-2.amazonaws.com/pythonapp
          ports:
            - containerPort: 3000
